# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: false
