services:
  db:
    container_name: api-db
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: simple_financial_api_development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: api-rails
    build:
      context: .
      dockerfile: config/docker/Dockerfile.development
    command: bash -c "bundle; bin/rails db:migrate; bin/rails s -b '0.0.0.0'"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - tmp_cache:/rails/tmp/cache
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/simple_financial_api_development
      TEST_DATABASE_URL: postgres://postgres:password@db:5432/simple_financial_api_test
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  bundle_cache:
  tmp_cache:
